# Generated by Django 6.0.6 on 2026-06-08 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("requirements", models.TextField()),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("FULL_TIME", "Full-time"),
                            ("PART_TIME", "Part-time"),
                            ("INTERNSHIP", "Internship"),
                            ("REMOTE", "Remote"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("salary_range", models.CharField(blank=True, max_length=100)),
                ("application_deadline", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recruiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="profiles.recruiterprofile",
                    ),
                ),
            ],
        ),
    ]
